version: '3.8'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: express_db
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD_FILE: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - webnet

  app:
    image: 7shinomiya/express-app-sample:c4baa661ef3239e0530351900980674d5e3497>
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER_FILE: root
      DB_PASSWORD_FILE: root
      DB_NAME: express_db
    depends_on:
      - mysql
    networks:
      - webnet

secrets:
  db_password:
    external: true
  db_user:
    external: true

networks:
  webnet:
    driver: overlay
volumes:
  mysql_data:
